Add exit 1

diff --git a/.github/workflows/all.yml b/.github/workflows/all.yml
--- a/.github/workflows/all.yml
+++ b/.github/workflows/all.yml
@@ -10,4 +10,4 @@ jobs:
     - if: ${{ github.event.workflow_run.conclusion == 'success' }}
       run: echo 'The triggering workflow succeeded'
     - if: ${{ github.event.workflow_run.conclusion == 'failure' }}
-      run: echo 'The triggering workflow failed'
+      run: echo 'The triggering workflow failed'; exit 1
